---
driver:
  name: digitalocean

verifier:
  name: inspec
  format: junit
  output: ./target/%{platform}_do_inspec_output.xml

provisioner:
  name: chef_zero

transport:
  ssh_key_only: true

platforms:
  - name: ubuntu-14-04-x64
    driver_config:
      size: 2gb
  - name: ubuntu-16-04-x64
    driver_config:
      size: 2gb
  - name: ubuntu-17-04-x64
    driver_config:
      size: 2gb
  - name: centos-6-x64
    driver_config:
      size: 2gb
  - name: centos-7-x64
    driver_config:
      size: 2gb

suites:
  - name: default
    run_list:
      - recipe[mule-test::default]
    attributes:
      aws:
        access_key: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        secret: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
