name             'mule'
maintainer       'Reed McCartney'
maintainer_email 'reed@hoegg.software'
license          'Apache License, Version 2.0'
description      'Installs/Configures Mule ESB'
long_description 'Installs/Configures Mule ESB'
version          '0.2.0'

depends 'apt', '~> 3.0.0'
depends 'java', '~> 1.39.0'
